import Head from 'next/head'
import Image from 'next/image';

function about() {
  return (
    <>

<Head>

<title>About</title>
<meta name="title" content="About title" />
<meta name="description"
  content="About description"
   />
<meta property="og:type" content="About" />
<meta property="og:url" content="https://www.gujaratvandan.com/" />
<meta property="og:title" content="About title"
/>
<meta property="og:description"
  content="About description"
/>
<meta property="og:image" content="https://secretseventeen.com/Media/icon.png" />
<meta property="twitter:card" content="summary_large_image" />
<meta property="twitter:url" content="https://www.gujaratvandan.com/" />
<meta property="twitter:title"
  content="About title" />
<meta property="twitter:description"
  content="Bout description"
/>
<meta property="twitter:image" content="https://secretseventeen.com/Media/icon.png" />

{/* ---- */}
{/* <title>Create Next App</title> */}
{/* <meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/favicon.ico" /> */}

</Head>
    <div>about</div>
    <Image
        src="https://secretseventeen.com/Media/icon.png"
        alt="My image"
        width={500}
        height={500}
      />

    </>
  )
}

export default about