import React from 'react'
import { FullNews } from '@/components/FullNews/FullNews'
import App from '@/components/Layout/App';
import axios from "axios";
import Head from "next/head";

function fullnews({ articles, data }) {
  // console.log("articles", data.response[0] );
  return (
    <>

      <Head>
        <title>{data.response[0].NewsTittle}</title>
        <meta name="title" content={data.response[0].NewsTittle} />
        <meta name="description" content={data.response[0].NewsSubTittle} />
        <meta property="og:type" content="article" />
        <meta property="og:url" content={process.env.NEXT_PUBLIC_API_URL + data.response[0].Path} />
        <meta property="og:title" content={data.response[0].NewsTittle} />
        <meta property="og:description" content={data.response[0].NewsSubTittle} />
        <meta
          property="og:image"
          content={process.env.NEXT_PUBLIC_API_URL + data.response[0].Path}
        />
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://www.gujaratvandan.com/" />
        <meta property="twitter:title" content={data.response[0].NewsTittle} />
        <meta property="twitter:description" content={data.response[0].NewsSubTittle} />
        <meta
          property="twitter:image"
          content={process.env.NEXT_PUBLIC_API_URL + data.response[0].Path}
        />

        {/* ---- */}
        {/* <title>Create Next App</title> */}
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <App>
        <FullNews value={{ data: articles }} />
      </App>
    </>
  )
}

export default fullnews


export async function getServerSideProps(context) {



  const { params } = context
  console.log(params);
  const { fullnews } = params
  // console.log(params);

  // const response = await fetch('https://secretseventeen.com/call/allNewsDataId',{data:fullnews} )

  const data = await axios
    .post(process.env.NEXT_PUBLIC_API_BASE_URL + "/allNewsDataId", {
      data: fullnews,
    })

  // .then(async(response)=> {
  console.log("datrr", data.data);

  // })


  // const data = await response.json()

  return {
    props: {
      articles: fullnews,
      data: data.data
    }
  }

}